### ISSUE TITLE
crawler option seems to hang

### ISSUE THREAD

**Issue by jpage4500** [adewaleng/node-apkpure-crawler#1]
Hi, first off thanks for writing this tool. I was hoping to use it to periodically (and programmatically) check if there's a new version of an app available from apkpure.

I'm running on a Mac and the `get` command seems to work fine but the `crawler` command prints out a warning and seems to hang.

Any ideas?

```
$ apkcrawl get com.ea.gp.fifamobile
https://d.apkpure.com/b/APK/com.ea.gp.fifamobile?version=latest

$ apkcrawl crawler com.ea.gp.fifamobile

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
```

**Comment by jpage4500** [comment]
edit.. I see there is a timeout that's displayed after waiting.. but still not working:
```
$ apkcrawl crawler com.ea.gp.fifamobile

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

apkcrawl crawler <pkg>

crawler package info with package name

Options:
  --help                 Show help                                     [boolean]
  --version              Show version number                           [boolean]
  --version-code, --vc   package version code                           [number]
  --with-versions, --wv  crawler app info with all versions download info
                                                                       [boolean]

Error: search com.ea.gp.fifamobile error: TimeoutError: Waiting for selector `.main .first` failed: Waiting failed: 30000ms exceeded
    at crawlerApkInfo (/opt/homebrew/lib/node_modules/apkpure-crawler/src/crawler-apk-info.js:13:11)
    at async Object.handler (/opt/homebrew/lib/node_modules/apkpure-crawler/bin/index.js:42:20)

$
```
